FROM docker.elastic.co/logstash/logstash:8.11.0

# Copy logstash pipeline config directly into image
COPY logstash/pipeline /usr/share/logstash/pipeline

# Environment variables
ENV LS_JAVA_OPTS="-Xms256m -Xmx256m"
ENV xpack.monitoring.enabled=false
